"""Turn results/*.json into paper/_numbers.tex (LaTeX \\newcommand macros).

Every number in the paper is generated here from measured results, so the paper
cannot drift from the experiments.  Run after experiments/run_all.py.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "_numbers.tex")


def load(name):
    p = os.path.join(RESULTS, name)
    return json.load(open(p)) if os.path.exists(p) else None


def pct(x):
    return f"{100 * x:.1f}"


def f3(x):
    return f"{x:.3f}"


def f4(x):
    return f"{x:.4f}"


def main():
    lines = ["% Auto-generated by scripts/paper_numbers.py: do not edit by hand.", ""]

    def cmd(name, val):
        # \renewcommand overrides the \providecommand defaults in the preamble, so
        # the paper always shows measured values when _numbers.tex is present.
        lines.append(f"\\renewcommand{{\\{name}}}{{{val}}}")

    planted = load("planted.json")
    if planted:
        m = planted["main"]
        cfg = planted["config"]
        cmd("nIn", cfg["n_in"]); cmd("nConcepts", cfg["K"])
        cmd("nRelevant", cfg["n_relevant"]); cmd("nClasses", cfg["n_classes"])
        cmd("dictM", cfg["m"]); cmd("topK", cfg["k"]); cmd("plantedSteps", cfg["steps"])

        cmd("candorFull", pct(m["acc_full"]))
        cmd("candorLegible", pct(m["acc_legible"]))
        cmd("opaqueAcc", pct(planted["tax"]["opaque_acc"]))
        cmd("taxPct", f"{100 * planted['tax']['tax']:.2f}")
        cmd("deltaMain", f4(m["delta_mean"]))
        cmd("deltaMainPct", f"{100 * m['delta_mean']:.2f}")
        cmd("deltaPNineFive", f4(m["delta_p95"]))
        cmd("agreeMain", pct(m["agreement"]))
        cmd("recovery", f3(m["recovery"]))
        cmd("recoveryMin", f3(m["recovery_min"]))
        cmd("monoMargin", f3(m["mono_margin"]))
        cmd("necGap", pct(m["necessity_gap"]))
        cmd("necRel", pct(m["necessity_relevant"]))
        cmd("necIrrel", pct(m["necessity_irrelevant"]))
        cmd("dirRel", pct(m["directional_relevant"]))
        cmd("dirIrrel", pct(m["directional_irrelevant_unchanged"]))
        cmd("leakSwapCandor", f4(m["leak_swap_effect"]))

        s = planted["opaque_sae"]
        cmd("saeRecovery", f3(s["sae_recovery"]))
        cmd("saeSubDelta", f4(s["sae_substitution_delta"]))
        cmd("saeResidualSwap", f4(s["sae_residual_swap_effect"]))
        ratio = s["sae_residual_swap_effect"] / max(1e-6, m["leak_swap_effect"])
        cmd("residualSwapRatio", f"{ratio:.0f}")

        ab = planted["ablations"]
        keymap = {"no_faith": "Faith", "no_leak": "Leak",
                  "no_causal": "Causal", "no_anchor": "Anchor"}
        for key, suff in keymap.items():
            a = ab[key]
            cmd(f"abl{suff}Delta", f4(a["delta_mean"]))
            cmd(f"abl{suff}Recovery", f3(a["recovery"]))
            cmd(f"abl{suff}NecGap", pct(a["necessity_gap"]))
            cmd(f"abl{suff}LeakSwap", f4(a["leak_swap_effect"]))

        cmd("stabAnchored", f3(planted["stability"]["anchored"]))
        cmd("stabFree", f3(planted["stability"]["free"]))

        t = planted["trojan"]
        cmd("trojanAuc", f3(t["auc_delta_detects_trojan"]))
        cmd("trojanDeltaClean", f4(t["delta_clean_mean"]))
        cmd("trojanDeltaTrojan", f4(t["delta_trojan_mean"]))
        sep = t["delta_trojan_mean"] / max(1e-6, t["delta_clean_mean"])
        cmd("trojanSeparation", f"{sep:.0f}")
        cmd("trojanRate", pct(t["trojan_rate"]))
        cmd("trojanAcc", pct(t["acc_full"]))

    seq = load("seq.json")
    if seq:
        cmd("seqLen", seq["seq_len"]); cmd("seqVocab", seq["vocab"])
        cmd("seqClasses", seq["n_classes"])
        cmd("seqAccFull", pct(seq["acc_full"]))
        cmd("seqAccLegible", pct(seq["acc_legible"]))
        cmd("seqTaxPct", f"{100 * seq['tax']:.2f}")
        cmd("seqDelta", f4(seq["delta_mean"]))
        cmd("seqAgree", pct(seq["agreement"]))
        cmd("seqTrain", seq["n_train"]); cmd("seqTest", seq["n_test"])

    gpt2 = load("gpt2.json")
    if gpt2:
        s, c = gpt2["sae"], gpt2["candor"]
        cmd("gptParams", f"{gpt2['params'] / 1e6:.0f}")
        cmd("gptLayer", gpt2["layer"]); cmd("gptNLayer", gpt2["n_layer"])
        cmd("gptValSeqs", gpt2["n_val"]); cmd("gptDictM", gpt2["m"]); cmd("gptTopK", gpt2["k"])
        cmd("gptSaeDelta", f4(s["delta"])); cmd("gptCandorDelta", f4(c["delta"]))
        cmd("gptSaeSwap", f4(s["leak_swap"])); cmd("gptCandorSwap", f4(c["leak_swap"]))
        cmd("gptSaeRecon", f3(s["recon_unexplained"])); cmd("gptCandorRecon", f3(c["recon_unexplained"]))
        cmd("gptSaeRecovered", pct(s["loss_recovered"])); cmd("gptCandorRecovered", pct(c["loss_recovered"]))
        cmd("gptLossFull", f3(c["loss_full"])); cmd("gptLossAbl", f3(c["loss_ablated"]))
        cmd("gptLossSaeLeg", f3(s["loss_legible"])); cmd("gptLossCandorLeg", f3(c["loss_legible"]))
        ratio = s["delta"] / max(1e-6, c["delta"])
        cmd("gptDeltaRatio", f"{ratio:.1f}")

    ft = load("gpt2_ft.json")
    if ft:
        s, c = ft["ft_sae"], ft["ft_candor"]
        cmd("ftSteps", ft["steps"])
        cmd("ftOrigLoss", f3(ft["orig_loss_full"]))
        cmd("ftSaeDelta", f4(s["delta"])); cmd("ftCandorDelta", f4(c["delta"]))
        cmd("ftSaeSwap", f4(s["leak_swap"])); cmd("ftCandorSwap", f4(c["leak_swap"]))
        cmd("ftSaeRecon", f3(s["recon_unexplained"])); cmd("ftCandorRecon", f3(c["recon_unexplained"]))
        cmd("ftSaeLoss", f3(s["loss_full"])); cmd("ftCandorLoss", f3(c["loss_full"]))
        fz = ft.get("frozen_reference")
        if fz:
            gain = fz["sae"]["recon_unexplained"] / max(1e-6, s["recon_unexplained"])
            cmd("ftReconGain", f"{gain:.0f}")

    sweep = load("gpt2_ft_sweep.json")
    if sweep:
        sm = sweep["summary"]
        cmd("ftSweepSeeds", len(sweep["seeds"]))
        cmd("ftSweepSaeDelta", f4(sm["ft_sae"]["delta"]["mean"]))
        cmd("ftSweepSaeDeltaStd", f4(sm["ft_sae"]["delta"]["std"]))
        cmd("ftSweepSaeSwap", f4(sm["ft_sae"]["leak_swap"]["mean"]))
        cmd("ftSweepSaeLoss", f3(sm["ft_sae"]["loss_full"]["mean"]))
        suffixes = ("Low", "Mid", "High")
        for w, suff in zip((str(x) for x in sweep["weightings"]), suffixes):
            c = sm["ft_candor"][w]
            cmd(f"ftSweepWeight{suff}", w)
            cmd(f"ftSweepCandorDelta{suff}", f4(c["delta"]["mean"]))
            cmd(f"ftSweepCandorDelta{suff}Std", f4(c["delta"]["std"]))
            cmd(f"ftSweepCandorSwap{suff}", f4(c["leak_swap"]["mean"]))
            cmd(f"ftSweepCandorLoss{suff}", f3(c["loss_full"]["mean"]))
        best = min(sm["ft_candor"].values(), key=lambda c: c["delta"]["mean"])
        cmd("ftSweepCandorDeltaBest", f4(best["delta"]["mean"]))

    lm = load("lm_scratch.json")
    if lm:
        cfg, sm = lm["config"], lm["summary"]
        cmd("lmLayers", cfg["n_layers"]); cmd("lmDModel", cfg["d_model"])
        cmd("lmHeads", cfg["n_heads"]); cmd("lmDMlp", cfg["d_mlp"])
        cmd("lmDictM", cfg["m"]); cmd("lmTopK", cfg["k"])
        cmd("lmSeqLen", cfg["seq_len"]); cmd("lmSteps", cfg["steps"])
        cmd("lmBatch", cfg["batch"]); cmd("lmSeeds", len(lm["seeds"]))
        cmd("lmTrainSeqs", lm["n_train"]); cmd("lmValSeqs", lm["n_val"])
        cmd("lmOpaqueLoss", f3(sm["opaque_loss_full"]["mean"]))
        cmd("lmOpaqueLossStd", f3(sm["opaque_loss_full"]["std"]))
        for cond, suff in (("recon", "Recon"), ("candor", "Candor"),
                           ("sae_final", "SaeFinal"), ("sae_all", "SaeAll")):
            s = sm[cond]
            cmd(f"lm{suff}Delta", f4(s["delta"]["mean"]))
            cmd(f"lm{suff}DeltaStd", f4(s["delta"]["std"]))
            cmd(f"lm{suff}Swap", f4(s["leak_swap"]["mean"]))
            cmd(f"lm{suff}SwapStd", f4(s["leak_swap"]["std"]))
            cmd(f"lm{suff}LegLoss", f3(s["loss_legible"]["mean"]))
            cmd(f"lm{suff}Agree", pct(s["agreement"]["mean"]))
            cmd(f"lm{suff}Recon", f3(s["recon_unexplained"]["mean"]))
        for cond, suff in (("recon", "Recon"), ("candor", "Candor")):
            vals = [r[cond]["final_site"]["delta"] for r in lm["runs"].values()]
            cmd(f"lm{suff}FinalDelta", f4(sum(vals) / len(vals)))
        cmd("lmReconLoss", f3(sm["recon"]["loss_full"]["mean"]))
        cmd("lmCandorLoss", f3(sm["candor"]["loss_full"]["mean"]))
        cmd("lmCandorTax", f3(sm["candor_tax"]["mean"]))
        cmd("lmCandorTaxStd", f3(sm["candor_tax"]["std"]))
        cmd("lmReconTax", f3(sm["recon_tax"]["mean"]))
        cmd("lmCandorTaxPct", f"{100 * sm['candor_tax']['mean'] / sm['opaque_loss_full']['mean']:.1f}")
        ratio = sm["recon"]["delta"]["mean"] / max(1e-6, sm["candor"]["delta"]["mean"])
        cmd("lmDeltaRatio", f"{ratio:.1f}")
        swap_ratio = sm["recon"]["leak_swap"]["mean"] / max(1e-6, sm["candor"]["leak_swap"]["mean"])
        cmd("lmSwapRatio", f"{swap_ratio:.1f}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    n = sum(1 for l in lines if l.startswith("\\renewcommand"))
    print(f"wrote {OUT} with {n} macros")


if __name__ == "__main__":
    main()
